"""
WAF Fingerprinting — detecta presença e tipo de WAF via headers, cookies e respostas a payloads.
"""
import requests
import warnings
from core.utils import print_status, safe_request

warnings.filterwarnings("ignore", message="Unverified HTTPS request")

WAF_SIGNATURES = {
    "Cloudflare": {
        "headers": ["cf-ray", "cf-cache-status", "cf-request-id"],
        "cookies": ["__cfduid", "cf_clearance"],
        "body":    ["Checking your browser", "cf-browser-verification"],
    },
    "AWS WAF": {
        "headers": ["x-amzn-requestid", "x-amz-cf-id"],
        "cookies": ["aws-waf-token"],
        "body":    ["AWS WAF"],
    },
    "ModSecurity": {
        "headers": ["mod_security", "modsecurity"],
        "body":    ["ModSecurity", "NOYB"],
    },
    "Akamai": {
        "headers": ["akamai-grn", "x-akamai-transformed"],
        "cookies": ["ak_bmsc", "bm_sv"],
        "body":    ["AkamaiGHost"],
    },
    "Imperva / Incapsula": {
        "headers": ["x-iinfo", "x-cdn"],
        "cookies": ["visid_incap", "incap_ses"],
        "body":    ["Incapsula"],
    },
    "F5 BIG-IP ASM": {
        "headers": ["x-cnection", "x-wa-info"],
        "cookies": ["TS", "BIGipServer"],
        "body":    ["The requested URL was rejected"],
    },
    "Sucuri": {
        "headers": ["x-sucuri-id", "x-sucuri-cache"],
        "body":    ["Sucuri WebSite Firewall"],
    },
    "Barracuda": {
        "headers": ["barra_counter_session"],
        "body":    ["You have been blocked","Barracuda"],
    },
    "Wordfence": {
        "body": ["Generated by Wordfence", "Wordfence"],
    },
}

PROBE_PAYLOADS = [
    "/?q=<script>alert(1)</script>",
    "/?id=1' OR '1'='1",
    "/?file=../../../../etc/passwd",
    "/?cmd=cat /etc/passwd",
]


class WAFDetector:
    def __init__(self, target: str):
        self.target  = target
        self.results = {"detected": False, "waf": None, "confidence": 0, "bypass_hints": []}

    def _check_response(self, r) -> list[str]:
        detected = []
        h_str = " ".join(f"{k.lower()}: {v.lower()}" for k, v in r.headers.items())
        c_str = " ".join(c.name.lower() for c in r.cookies)
        body  = r.text.lower()

        for waf, sigs in WAF_SIGNATURES.items():
            score = 0
            for h in sigs.get("headers", []):
                if h.lower() in h_str:
                    score += 2
            for c in sigs.get("cookies", []):
                if c.lower() in c_str:
                    score += 2
            for b in sigs.get("body", []):
                if b.lower() in body:
                    score += 3
            if score >= 2:
                detected.append((waf, score))

        return detected

    def probe(self):
        print_status("WAF Fingerprinting...", "INFO")
        all_detected = {}

        # Requisição normal primeiro
        r = safe_request(self.target)
        if r:
            for waf, score in self._check_response(r):
                all_detected[waf] = all_detected.get(waf, 0) + score

        # Probes com payloads suspeitos
        for path in PROBE_PAYLOADS:
            url = self.target.rstrip("/") + path
            try:
                resp = requests.get(url, timeout=6, verify=False,
                                    headers={"User-Agent": "Mozilla/5.0"})
                for waf, score in self._check_response(resp):
                    all_detected[waf] = all_detected.get(waf, 0) + score

                # Status 403/406/429/503 com payload suspeito = WAF genérico
                if resp.status_code in (403, 406, 429, 503) and not all_detected:
                    all_detected["Generic WAF"] = all_detected.get("Generic WAF", 0) + 3
            except Exception:
                pass

        if all_detected:
            best = max(all_detected, key=all_detected.get)
            self.results["detected"]   = True
            self.results["waf"]        = best
            self.results["confidence"] = min(all_detected[best] * 10, 100)
            self.results["all"]        = all_detected
            self.results["bypass_hints"] = self._bypass_hints(best)
            print_status(f"WAF detectado: {best} (confiança: {self.results['confidence']}%)", "WARN")
        else:
            print_status("Nenhum WAF detectado.", "SUCCESS")

        return self.results

    def _bypass_hints(self, waf: str) -> list[str]:
        hints = {
            "Cloudflare": [
                "Tentar payloads com encoding duplo (URL + HTML)",
                "Usar case variation: <ScRiPt>",
                "Testar via origin IP direto (bypass CDN)",
            ],
            "ModSecurity": [
                "Testar encoding UTF-8 de payloads",
                "HTTP Parameter Pollution",
                "Comentários SQL: /*!SELECT*/",
            ],
            "Generic WAF": [
                "Testar payloads encodados em base64",
                "Variar User-Agent e headers",
            ],
        }
        return hints.get(waf, ["Analisar manualmente padrões de resposta."])
